### ISSUE TITLE
unfinished import and hight workload (on a low resources rpi400)

### ISSUE THREAD

**Issue by ippocratis** [alextran1502/immich-cli#1]
after an error
```/bin/sh: line 1: hostname: command not found```
it starts upload
```
[1] Pinging server...
Server status: OK
[2] Logging in...
Login status: OK
You are logged in as xxxxxxxx@tutanota.com
[3] Checking directory...
Directory status: OK
[4] Indexing files...
Indexing file: OK
Found 150 assets in specified directory
[5] Gathering device's asset info from server...
A total of 150 assets will be uploaded to the server
Do you want to start upload now? (y/n) y
Start uploading...
 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | ETA: 0s | 0/150```
```

throws some errors

```
Error uploading asset Error: No duration found!
```

but the percentage increasess

unfortunately it stops in the middle of "uploading" with 

```
 ████████████████████░░░░░░░░░░░░░░░░░░░░ 49% | ETA: 102s | 74/150
Error uploading asset Error: Request failed with status code 504
```
cpu load was constantly at 98-100% during the proccess

i would be happy to provide any source of logs etc 

eta  is not acurate : it was more like 10 minutes
also count (75/150) is not acurate 125 photos actually imported

**Comment by alextran1502** [comment]
Can you help me check which version is it? 

`immich --version`

**Comment by ippocratis** [comment]
@alextran1502 
Version 0.3.0
8 mp4
142jpg
16of them was already uploaded from the phone app
So...
Was actually all imported?
It did not included the files already there?

**Comment by alextran1502** [comment]
The folder is indexed and compared with the database so whenever you run the command, it will only upload the one that hasn't been uploaded. 

I think there might be a problem with FFmpeg on the Pi400 that caused the `No duration found!` error.

The high CPU workload is because it is trying to upload as fast as possible, so the CPU will be used 100% of its processing power to upload multiple files at the same time, which includes, gathering the file stats and reading the file from the filesystem to perform the upload operation.

**Comment by ShiniGandhi** [comment]
I'm getting the same error with an x86_64-based server.

**Comment by alextran1502** [comment]
@ShiniGandhi This repo is not up to date with the main Immich repo at the moment. I was gonna re-write it at a later time. Will keep you posted

**Comment by alextran1502** [comment]
CLI tool is now updated with version 0.4.0
